sudo: required
language: node_js
node_js: 5.7.1
env:
  dev: NODE_ENV=TEST
before_script: 
- npm install -g karma
- npm install 
script: 
- karma start karma.conf.js --single-run
- npm run lint
notifications:
  slack: gitwrecked:OEXOs5wkTZglJKfqGC7edOau