version: '2'

services:  
  client: 
    build: 
      context: ./client
      dockerfile: client.dockerfile
    volumes:
      - /cardash/client     
    ports:
      - "4200:4200" 
  server: 
    build: 
      context: ./server
      dockerfile: server.dockerfile
    volumes:
      - /cardash/server     
    ports:
      - "3001:3001" 
    links:
      - database 
  database: 
    image: mongo 
    ports:
      - "27017:27017"