version: '2'

services:  
  client: 
    image: node:6
    volumes:
      - ./client:/cardash/client/     
    working_dir: /cardash/client/
    command: npm run start-dev
    environment:
      - SERVER=http://192.168.59.103:3001
    networks:
      - front
      - back
  server: 
    image: node:6
    volumes:
      - ./server:/cardash/server/  
    working_dir: /cardash/server/  
    command: npm run start-dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URI=mongodb://database/test
    ports:
      - "3001:3001" 
    links:
      - database 
    networks:
      - front
  database: 
    image: mongo 
    networks:      
      - back

networks:
    back:
      driver: bridge
    front:
      driver: bridge